import axios from "axios";
import Head from "next/head";
import { ChangeEvent, useEffect, useState } from "react";
import GameMenu from "~/components/GameMenu";
import { useSocketState } from "~/hooks/useSocketState";
import { setRoomId } from "~/state/globalSlice";
import { useAppDispatch, useAppSelector } from "~/utils/hooks";
import { socket } from "~/utils/socket";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [value, setValue] = useState("");
  const [moves, setMoves] = useState<string[]>([]);
  const { isConnected } = useSocketState();
  const [errorMsg, setErrorMsg] = useState("");
  const [gameJoined, setGameJoined] = useState(false);
  const [gameStarted, setGameStarted] = useState(false);
  const dispatch = useAppDispatch();
  const { roomId } = useAppSelector((state) => state.global);

  useEffect(() => {
    const socketInit = async () => {
      await axios.get("/api/socket");
      socket.connect();
      socket.on(
        "joined-game",
        ({
          status,
          message,
          id,
        }: {
          status: boolean;
          message: string;
          id: string;
        }) => {
          setGameJoined(true);
          status && dispatch(setRoomId(id));
          if (!status) setErrorMsg(message);
        }
      );

      socket.on("start-game", ({ status }: { status: boolean }) => {
        setGameStarted(status);
      });

      socket.on(
        "created-game",
        ({ status, id }: { status: boolean; id: string }) => {
          status && dispatch(setRoomId(id));
          status && setGameJoined(true);
        }
      );
      setErrorMsg("");
    };
    socketInit().catch(console.error);

    return () => {
      socket.disconnect();
      socket.emit("disconnectt");
      console.log("first");
    };
  }, []);

  useEffect(() => {
    socket.on("game-update", (data) => {
      setMoves([...moves, data]);
    });
  }, [moves]);

  const onChangeHandler = (event: ChangeEvent<HTMLInputElement>) => {
    setValue(event.target.value);
  };

  const onSendMessage = (value: string) => {
    socket.emit("game-update", roomId, value);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            {isConnected ? "Connected" : "Not Connected"}
          </h1>
          <GameMenu />
          <p className="text-red-600">{errorMsg}</p>
          {gameStarted && (
            <div>
              <input
                className="text-black"
                type="text"
                value={value}
                onChange={(e) => onChangeHandler(e)}
                disabled={!gameStarted}
              />
              <button className="" onClick={() => onSendMessage(value)}>
                SEND
              </button>
            </div>
          )}
          <div className="flex flex-col">
            {moves.map((move, index) => (
              <div key={index}>{move}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
